"""
Email Alert Engine — Send daily A+ swing trade setups via SMTP
"""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Dict, List


class AlertEngine:
    """Send trade alerts via email"""

    def __init__(self, smtp_server="smtp.gmail.com", smtp_port=587,
                 sender_email="", sender_password="", recipient_email=""):
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
        self.sender_email = sender_email
        self.sender_password = sender_password
        self.recipient_email = recipient_email

    def send_alerts(self, results: List[Dict], subject_prefix: str = "") -> bool:
        """Send email with A+ trade setups"""
        if not results:
            return False
        try:
            a_plus = [r for r in results if r.get('is_a_plus')]
            all_signals = sorted(results, key=lambda x: x['total_score'], reverse=True)

            html = f"""<html>
<head><style>
body {{ font-family: 'Segoe UI', Arial, sans-serif; background:#0d1117; color:#c9d1d9; padding:20px; }}
h1 {{ color: #58a6ff; }}
h2 {{ color: #3fb950; }}
.card {{ background:#161b22; border:1px solid #30363d; border-radius:8px; padding:15px; margin:10px 0; }}
.a-plus {{ border-left: 4px solid #3fb950; }}
.buy {{ border-left: 4px solid #58a6ff; }}
.metric {{ display:inline-block; margin:0 15px; text-align:center; }}
.metric .value {{ font-size:1.2em; font-weight:bold; color:#58a6ff; }}
.green {{ color:#3fb950; }} .red {{ color:#f85149; }} .yellow {{ color:#d2991d; }}
table {{ border-collapse:collapse; width:100%; margin:10px 0; }}
th {{ background:#21262d; padding:8px; text-align:left; border-bottom:2px solid #30363d; }}
td {{ padding:8px; border-bottom:1px solid #30363d; }}
</style></head><body>
<h1>📊 Swing Trade Alerts</h1>
<p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} | Total scanned: {len(results)}</p>
"""

            if a_plus:
                html += f"<h2>🏆 A+ Setups ({len(a_plus)} found)</h2>"
                for r in a_plus:
                    atr = r.get('details', {}).get('atr_risk', {})
                    html += f"""<div class="card a-plus">
<h3>🏆 {r['symbol']} — {r['signal']} (Grade: {r['grade']})</h3>
<p>Score: <b>{r['total_score']}/180</b> | Price: <b>${r['current_price']}</b></p>
<p>
<span class="metric"><span class="red">🛑 Stop:</span> <span class="value">${atr.get('suggested_stop','?'):.2f}</span></span>
<span class="metric"><span class="yellow">🎯 50%:</span> <span class="value">${atr.get('half_profit_price','?'):.2f}</span></span>
<span class="metric"><span class="green">🚀 100%:</span> <span class="value">${atr.get('full_profit_price','?'):.2f}</span></span>
</p>
</div>"""

            html += "<h2>📋 All Signals</h2><table>"
            html += "<tr><th>Symbol</th><th>Score</th><th>Signal</th><th>Grade</th><th>Price</th><th>Stop Loss</th><th>Half TP</th><th>Full TP</th></tr>"
            for r in all_signals[:20]:
                atr = r.get('details', {}).get('atr_risk', {})
                emoji = "🏆" if r['grade'] == 'A+' else "✅" if r['grade'] == 'A' else "📊" if r['grade'] == 'B' else "👀" if r['grade'] == 'C' else "➖"
                html += f"""<tr>
<td><b>{r['symbol']}</b></td>
<td>{r['total_score']}</td>
<td>{r['signal']}</td>
<td>{emoji} {r['grade']}</td>
<td>${r['current_price']:.2f}</td>
<td class="red">${atr.get('suggested_stop','?'):.2f}</td>
<td class="yellow">${atr.get('half_profit_price','?'):.2f}</td>
<td class="green">${atr.get('full_profit_price','?'):.2f}</td>
</tr>"""
            html += "</table><p style='color:#8b949e; font-size:0.8em;'>Auto-generated by Stock Trader</p></body></html>"

            msg = MIMEMultipart("alternative")
            msg['Subject'] = f"{subject_prefix} 🔔 A+ Setups ({len(a_plus)}) | {datetime.now().strftime('%b %d')}"
            msg['From'] = self.sender_email
            msg['To'] = self.recipient_email
            msg.attach(MIMEText(html, 'html'))

            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.sendmail(self.sender_email, [self.recipient_email], msg.as_string())
            return True
        except Exception as e:
            print(f"Alert send failed: {e}")
            return False
